default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS", 5) %>


# Development environment
development:
  <<: *default
  database: skillzone_api_development
  username: skillzone_api
  password: ZoneSkill456
  host: localhost
  port: 5432


# Test environment
test:
  <<: *default
  database: skillzone_api_test


# Production environment (Render)
production:
  url: <%= ENV.fetch("DATABASE_URL") %>
