default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

# Development enviroment
development:
  <<: *default
  database: skillzone_api_development
  username: skillzone_api
  password: ZoneSkill456
  host: localhost
  port: 5432

# Test enviorment
test:
  <<: *default
  database: skillzone_api_test

# Production enviroment
production:
  <<: *default
  url: <%= ENV["DATABASE_URL"] %>


# As with config/credentials.yml, you never want to store sensitive information,
# like your database password, in your source code. If your source code is
# ever seen by anyone, they now have access to your database.
#
# Instead, provide the password or a full connection URL as an environment
# variable when you boot the app. For example:
#
#   DATABASE_URL="postgres://myuser:mypass@localhost/somedatabase"
#
# If the connection URL is provided in the special DATABASE_URL environment
# variable, Rails will automatically merge its configuration values on top of
# the values provided in this file. Alternatively, you can specify a connection
# URL environment variable explicitly:
